services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gatherin-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - gatherin-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gatherin-backend
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - gatherin-network

networks:
  gatherin-network:
    driver: bridge
