services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gatherin-frontend
    ports:
      - "3000:3000"
    env_file:
      - /opt/gatherin/.env
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gatherin-backend
    ports:
      - "8000:8000"
    env_file:
      - /opt/gatherin/.env
    restart: unless-stopped

