services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gatherin-frontend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      DATABASE_URL_BACK: ${DATABASE_URL_BACK}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gatherin-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL_BACK: ${DATABASE_URL_BACK}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    restart: always
