version: '3.8'

services:
  frontend:
    image: YOUR_DOCKERHUB_USERNAME/gatherin-frontend:latest
    container_name: gatherin-frontend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    restart: unless-stopped
    networks:
      - gatherin-network

  backend:
    image: YOUR_DOCKERHUB_USERNAME/gatherin-backend:latest
    container_name: gatherin-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL_BACK=${DATABASE_URL_BACK}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    networks:
      - gatherin-network

networks:
  gatherin-network:
    driver: bridge
