services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - /opt/gatherin/.env
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - /opt/gatherin/.env
    ports:
      - "8000:8000"
